export default 'unneeded export'; //DEAD CODE - EXPORTED BUT NOT USED

console.log('my_side_effect_demo'); // SIDEFFECTS ARE THE CODE IN THE MODULE BUT NOT EXPORTED. IT WILL BE EXECUTED AUTONATICALLY ONCE THE MODULE IS EXPORTED.
